name: "Deploy site to Github Pages"

on: [workflow_dispatch, push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site branch
        uses: actions/checkout@v2

      - name: Install languages
        uses: asdf-vm/actions/install@v1

      - name: Install libraries
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: site
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
